name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
          dotnet-version: '7.0'
          include-prerelease: true
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        
    - name: Build the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker build . --file ValuationService/Dockerfile --tag ${DOCKER_USER}/valuation-service:latest-dev
      
    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
      run: docker push ${DOCKER_USER}/valuation-service:latest-dev
